#!/usr/bin/env bash
set -euo pipefail

# SPEC: COMP-DEB-PACKAGING-027 FR-1 FR-2 FR-5

usage() {
  cat <<'USAGE'
Usage:
  create-deb-packages.sh --version <version> [--arch <amd64|arm64>] [--output-dir <dir>] [--knot-bin <path>] [--knotd-bin <path>]
USAGE
}

version=""
arch="amd64"
output_dir="dist"
knot_bin="src-tauri/target/release/knot"
knotd_bin="src-tauri/target/release/knotd"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="${2:-}"; shift 2 ;;
    --arch) arch="${2:-}"; shift 2 ;;
    --output-dir) output_dir="${2:-}"; shift 2 ;;
    --knot-bin) knot_bin="${2:-}"; shift 2 ;;
    --knotd-bin) knotd_bin="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$version" ]]; then
  echo "--version is required" >&2
  usage
  exit 1
fi

if [[ ! -f "$knot_bin" || ! -f "$knotd_bin" ]]; then
  echo "missing binaries: knot=$knot_bin knotd=$knotd_bin" >&2
  exit 1
fi

mkdir -p "$output_dir"
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

build_one() {
  local pkg="$1"
  local bin_path="$2"
  local depends="$3"

  local root="$workdir/${pkg}_${version}_${arch}"
  mkdir -p "$root/DEBIAN" "$root/usr/bin"
  cp "$bin_path" "$root/usr/bin/$pkg"
  chmod 755 "$root/usr/bin/$pkg"

  cat > "$root/DEBIAN/control" <<CTRL
Package: $pkg
Version: $version
Section: utils
Priority: optional
Architecture: $arch
Maintainer: Knot Contributors <maintainers@knot.invalid>
Depends: $depends
Description: $pkg binary for Knot
 Generated by create-deb-packages.sh
CTRL

  dpkg-deb --build "$root" "$output_dir/${pkg}_${version}_${arch}.deb" >/dev/null
}

build_one "knot" "$knot_bin" "libc6, libgcc-s1, libwebkit2gtk-4.1-0, libjavascriptcoregtk-4.1-0, libgtk-3-0 | libgtk-3-0t64"
build_one "knotd" "$knotd_bin" "libc6, libgcc-s1"

printf '%s\n' "$output_dir/knot_${version}_${arch}.deb"
printf '%s\n' "$output_dir/knotd_${version}_${arch}.deb"
