#!/usr/bin/env bash
set -euo pipefail

# SPEC: COMP-DEB-PACKAGING-027 FR-3 FR-4 FR-5

usage() {
  cat <<'USAGE'
Usage:
  create-deb-source.sh --version <version> [--output-dir <dir>]
USAGE
}

version=""
output_dir="dist"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) version="${2:-}"; shift 2 ;;
    --output-dir) output_dir="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$version" ]]; then
  echo "--version is required" >&2
  usage
  exit 1
fi

command -v dpkg-source >/dev/null || { echo "dpkg-source is required" >&2; exit 1; }

mkdir -p "$output_dir"
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

srcdir="$workdir/knot-$version"
mkdir -p "$srcdir"
cp -R packaging/debian "$srcdir/debian"

# minimal source tree scaffold
cat > "$srcdir/README.md" <<'DOC'
# knot

Debian source package scaffold generated by scripts/create-deb-source.sh.
DOC

date_rfc2822="$(date -R)"
sed -e "s/@@VERSION@@/$version/g" -e "s#@@DATE@@#$date_rfc2822#g" \
  packaging/debian/changelog.in > "$srcdir/debian/changelog"

rm -f "$srcdir/debian/changelog.in"

(
  cd "$workdir"
  tar --exclude='knot-*/debian' -czf "knot_${version}.orig.tar.gz" "knot-$version"
  dpkg-source -b "knot-$version" >/dev/null
)

cp "$workdir"/knot_"$version".orig.tar.gz "$output_dir/"
cp "$workdir"/knot_"$version"-1.debian.tar.* "$output_dir/" 2>/dev/null || true
cp "$workdir"/knot_"$version"-1.dsc "$output_dir/"

ls -1 "$output_dir"/knot_"$version"* | sed -n '1,20p'
